import { buildBazi } from '../src/engines/bazi.js';
import { buildZiwei } from '../src/engines/ziwei.js';
import { baziPro, ziweiPro } from '../src/engines/pro.js';
import { buildLifeMap } from '../src/engines/lifemap.js';
const b = buildBazi({ date: '1990-05-20', time: '14:30', gender: '男' });
const z = buildZiwei({ date: '1990-05-20', time: '14:30', gender: '男' });
const p = baziPro(b);
console.log('== 八字专业盘 ==');
p.pillars.forEach(x => console.log(` ${x.pos}柱 ${x.gan}${x.zhi} | 藏干: ${x.hideDetail.map(h=>`${h.gan}(${h.weightLabel}·${h.shiShen})`).join(' ')} | 日主长生: ${x.changSheng.name}`));
p.notes.forEach(n => console.log('  ·', n));
console.log('\n== 紫微专业盘（命宫三方四正）==');
const zp = ziweiPro(z, '命宫');
zp.trine.forEach(t => console.log(` ${t.role}: ${t.palace.name} ${t.palace.stem}${t.palace.branch} | ${t.palace.majorStars.map(s=>s.name+(s.brightness||'')).join(' ')||'(空)'}`));
zp.notes.forEach(n => console.log('  ·', n));
console.log('\n== 官禄宫三方四正 ==');
ziweiPro(z, '官禄').trine.forEach(t => console.log(` ${t.role}: ${t.palace.name} | ${t.palace.majorStars.map(s=>s.name).join(' ')||'(空)'}`));
console.log('\n== 人生地图 ==');
const lm = buildLifeMap(b, z, '男');
console.log(' 年龄范围:', lm.minAge, '-', lm.maxAge, '| 阶段数:', lm.stages.length, '| 维度带:', lm.bands.length, '| 最大分:', lm.maxScore);
console.log(' 刻度:', lm.ticks.map(t=>t.age).join(' '));
console.log(' 峰值:', lm.peaks.map(p=>`${p.stage.startAge}-${p.stage.endAge}岁 ${p.domain.label}(${p.score})`).join(' | '));
console.log(' 概述:', lm.summary);
const allIn = lm.bands.every(bd => bd.points.every(pt => pt.x0 >= lm.pad-1 && pt.x1 <= lm.width-lm.pad+1 && pt.h >= 2));
console.log(' 所有图元在画布内:', allIn);
