// 三层分工：排盘算事实 / 规则标信号 / DSH 写解读；真太阳时；解读写回协议
import { buildBazi } from '../src/engines/bazi.js';
import { buildZiwei } from '../src/engines/ziwei.js';
import { resolvePlace, solarCorrection, correctedBirth, equationOfTime } from '../src/engines/solar.js';
import { chartSignals, yearSignals, signalsToText, yearToText } from '../src/engines/signals.js';
import { buildRequest, toolPrompt, hashOf, profileFacts } from '../src/dsh/facts.js';
import { castForQuestion, liuyaoFacts } from '../src/engines/cast.js';
import { contextDocument } from '../src/dsh/context-entry.js';
import * as S from '../src/store/store.js';
import { tenGodWuxing } from '../src/data/colors.js';
import { surnameFacts, nameMaterial, nameRules, parseNamesFromText, checkName } from '../src/engines/naming.js';
import { placeFacts, placeFactsText, cityFacts } from '../src/engines/places.js';
import { resolveActivity } from '../src/data/activities.js';
import { scoreDay, almanacOf } from '../src/engines/almanac.js';

if (typeof localStorage === 'undefined') {
  const mem = {};
  globalThis.localStorage = { getItem: k => (k in mem ? mem[k] : null), setItem: (k, v) => { mem[k] = String(v); }, removeItem: k => { delete mem[k]; } };
}
let pass = 0, fail = 0;
const ok = (name, cond, extra = '') => { cond ? (pass++, console.log('  ✓', name)) : (fail++, console.log('  ✗', name, extra)); };
const DOOM = /必然|一定会|注定|宣判|劫(?!财)|灾|凶|必将|逃不掉|完蛋|克夫|克妻/;
const GARBAGE = /\[object Object\]|undefined|NaN/;
const noTone = t => t.replace(/不说必然和注定|不说「必然、一定、注定、命中」，不说「劫、灾、凶、破财、克夫、克妻」/g, '');

console.log('\n[1] 出生地 → 经度 → 真太阳时');
ok('浙江 杭州 → 杭州', resolvePlace('浙江 杭州')?.name === '杭州' && Math.abs(resolvePlace('浙江 杭州').lng - 120.2) < 0.01);
ok('乌鲁木齐市 → 87.6', resolvePlace('新疆乌鲁木齐市')?.lng === 87.6);
ok('只写省份 → 省会', resolvePlace('河北')?.source === 'province' && resolvePlace('河北').lng === 114.5);
ok('吉林市 优先于 吉林省', resolvePlace('吉林市')?.lng === 126.6 && resolvePlace('吉林省')?.lng === 125.3);
ok('海外城市带时区', resolvePlace('东京')?.tz === 9 && resolvePlace('纽约')?.tz === -5);
ok('认不出返回 null', resolvePlace('火星基地') === null && resolvePlace('') === null);
const eot = equationOfTime(2000, 2, 11); ok('均时差 2 月中旬约 -14 分', eot < -12 && eot > -16, String(eot));
const wlmq = solarCorrection({ date: '2000-06-21', time: '12:00', lng: 87.6 });
ok('乌鲁木齐夏至正午：偏差约 -130 分', wlmq.offsetMin < -120 && wlmq.offsetMin > -140 && wlmq.time === '09:50' || (wlmq.offsetMin < -120 && wlmq.offsetMin > -140), JSON.stringify(wlmq));
const hz = solarCorrection({ date: '1991-08-08', time: '10:00', lng: 120.2 });
ok('杭州偏差在 ±10 分内', Math.abs(hz.offsetMin) <= 10, JSON.stringify(hz));
const shift = solarCorrection({ date: '2000-06-21', time: '00:30', lng: 87.6 });
ok('凌晨在乌鲁木齐 → 退到前一日', shift.date === '2000-06-20' && shift.dayShift === -1, JSON.stringify(shift));
const tokyo = solarCorrection({ date: '2000-06-21', time: '12:00', lng: 139.7, tz: 9 });
ok('东京按 UTC+9 参照 135°', Math.abs(tokyo.lngMin - 19) <= 1, JSON.stringify(tokyo));

console.log('\n[2] 档案层：什么时候校正、什么时候不校正');
const base = { birth_date: '1995-03-03', birth_time: '13:00', gender: '女', source: 'birth' };
const c1 = correctedBirth({ ...base, birth_place: '乌鲁木齐' });
ok('有出生地 → 校正', c1.applied && c1.place === '乌鲁木齐' && c1.note.includes('真太阳时'));
ok('时辰不详 → 不校正', !correctedBirth({ ...base, birth_place: '乌鲁木齐', time_unknown: true }).applied);
ok('四柱直录 → 不校正', !correctedBirth({ ...base, birth_place: '乌鲁木齐', source: 'pillars' }).applied);
ok('认不出的地名 → 不校正但有提示', !correctedBirth({ ...base, birth_place: '火星' }).applied && correctedBirth({ ...base, birth_place: '火星' }).note.includes('没认出'));
ok('手填经度 → 校正', correctedBirth({ ...base, birth_place: '火星', birth_lng: 90 }).applied);
ok('关掉开关 → 不校正', !correctedBirth({ ...base, birth_place: '乌鲁木齐', solar_correction: false }).applied);
let st = S.createProfile({ ...S.EMPTY }, { name: '测', ...base, birth_place: '乌鲁木齐' }).state;
const dc = S.deriveCharts(S.activeProfile(st));
const plain = buildBazi({ date: base.birth_date, time: base.birth_time, gender: '女' });
ok('deriveCharts 返回 corr 且时柱因校正而变', dc.corr.applied && dc.bazi.pillars[3].zhi !== plain.pillars[3].zhi, `${dc.bazi.pillars[3].zhi} vs ${plain.pillars[3].zhi}`);
ok('年月日柱不变', dc.bazi.pillars.slice(0, 3).map(p => p.gan + p.zhi).join() === plain.pillars.slice(0, 3).map(p => p.gan + p.zhi).join());

console.log('\n[3] 规则引擎：只标信号，六个方面齐全');
const bz = buildBazi({ date: '1991-08-08', time: '10:00', gender: '女' });
const zw = buildZiwei({ date: '1991-08-08', time: '10:00', gender: '女' });
const sig = chartSignals(bz, zw);
const groups = new Set(sig.map(s => s.group));
ok('信号分组齐全', ['日主', '五行', '十神', '紫微'].every(g => groups.has(g)), [...groups].join(','));
ok('每条信号有 label/value', sig.every(s => s.label && s.value !== undefined && s.value !== ''));
ok('信号文本无垃圾字符', !GARBAGE.test(signalsToText(sig)), signalsToText(sig).match(/.{20}(undefined|NaN).{20}/)?.[0]);
const ys = yearSignals(bz, zw, '女', 2026);
ok('今年六个方面都在', ys.domains.length === 6 && ys.domains.every(d => typeof d.level === 'string' && d.label));
ok('年份文本包含六个方面', ['事业', '财富', '关系', '迁移', '创造', '身心'].every(w => yearToText(ys).includes(w)));
ok('无大运时返回 null', yearSignals({ ...bz, daYun: [] }, zw, '女', 2026) === null);

console.log('\n[4] 给 DSH 的请求');
const prof = { name: '测', gender: '女', birth_date: '1991-08-08', birth_time: '10:00', birth_place: '杭州' };
const corr = correctedBirth(prof);
const ctx = { profile: prof, bazi: bz, ziwei: zw, corr, gender: '女' };
const reveal = buildRequest('reveal', ctx);
ok('reveal：key / 写回路径 / 六个方面', reveal.key === 'reveal' && reveal.prompt.includes('#reveal') && reveal.prompt.includes('interpretations["reveal"]') && ['事业', '财富', '关系', '迁移', '创造', '身心'].every(w => reveal.prompt.includes(w)));
ok('reveal 提示词带真太阳时说明', reveal.prompt.includes('真太阳时'));
const who = buildRequest('who', ctx);
ok('who：三张结论的小标题', ['最像自己的时候', '最容易吃亏的地方', '反复出现的矛盾'].every(w => who.prompt.includes(w)));
const wt = buildRequest('where-to', ctx);
ok('where-to：十年逐年信号', wt.prompt.includes('2035') && wt.prompt.includes('未来十年'));
const yr = buildRequest('year', { ...ctx, year: 2028 });
ok('year：key 带年份', yr.key === 'year:2028' && yr.prompt.includes('2028 年'));
const cast = castForQuestion('要不要去北京');
ok('起卦：六爻与梅花都有事实文本', cast.liuyao.text.includes('本卦') && cast.liuyao.text.includes('世爻') && cast.meihua.text.includes('体卦') && cast.liuyao.gua.ben.name);
const ev = { event_id: 'evt_t', question: '要不要去北京', cast };
const er = buildRequest('event', { ...ctx, event: ev });
ok('event：问题 + 卦 + 追问许可', er.key === 'event:evt_t' && er.prompt.includes('要不要去北京') && er.prompt.includes(cast.liuyao.gua.ben.name) && er.prompt.includes('最多追问'));
const pr = buildRequest('person', { ...ctx, person: { person_id: 'p1', nickname: '他', kindLabel: '伴侣' }, relation: { themPillars: '庚午 戊子 甲寅 丙寅', themDayMaster: '甲', themSoul: '', ganRel: '对方生我', zhiRels: '', palaceRels: '', dims: ['- 驱动：我 60 / 对方 40'] } });
ok('person：不给分数、不下结论', pr.key === 'person:p1' && pr.prompt.includes('不给契合度分数'));
ok('hash 稳定且随事实变化', reveal.hash === buildRequest('reveal', ctx).hash && reveal.hash !== buildRequest('reveal', { ...ctx, profile: { ...prof, birth_place: '乌鲁木齐' }, corr: correctedBirth({ ...prof, birth_place: '乌鲁木齐' }) }).hash);
const tp = toolPrompt('六爻', liuyaoFacts(cast.liuyao.gua, '甲子'), '换工作');
ok('工具阁提示词', tp.startsWith('【工具阁】六爻') && tp.includes('换工作') && tp.includes('本卦'));
ok('所有提示词无垃圾字符与断言词', ![reveal, who, wt, yr, er, pr].some(r => GARBAGE.test(r.prompt) || DOOM.test(noTone(r.prompt))), [reveal, who, wt, yr, er, pr].map(r => noTone(r.prompt).match(/.{15}(必然|一定会|注定|宣判|灾|凶|undefined|NaN).{15}/)?.[0]).filter(Boolean).join(' | '));

console.log('\n[5] 写回协议（store）');
st = S.createProfile({ ...S.EMPTY }, { name: '测', ...base }).state;
const pid = S.activeProfile(st).profile_id;
st = S.requestInterpretation(st, pid, 'reveal', 'h1');
let it = S.activeProfile(st).interpretations.reveal;
ok('请求 → pending + request.hash', it.status === 'pending' && it.request.hash === 'h1' && it.request.at);
st = S.setInterpretation(st, pid, 'reveal', { status: 'done', text: '## 事业\n多半……', at: '2026-09-09T00:00:00Z' });
it = S.activeProfile(st).interpretations.reveal;
ok('写回 → done，request 仍在', it.status === 'done' && it.text.includes('事业') && it.request.hash === 'h1');
st = S.requestInterpretation(st, pid, 'reveal', 'h2');
it = S.activeProfile(st).interpretations.reveal;
ok('事实变了再请求 → pending 但保留旧 text', it.status === 'pending' && it.request.hash === 'h2' && it.text.includes('事业'));
const cq = S.createQuestion(st, { question: '下半年适不适合换方向？', cast });
st = cq.state;
ok('createQuestion：问题即事件，卦随之固定', cq.event.event_type === 'question' && cq.event.cast.liuyao.text && S.activeProfile(st).events[0].question.includes('换方向'));
ok('blankProfile 有 interpretations / birth_lng', 'interpretations' in S.blankProfile() && 'birth_lng' in S.blankProfile());

console.log('\n[6] CONTEXT.md');
const doc = contextDocument({ ...prof, interpretations: { reveal: { status: 'pending', request: { hash: 'x', at: '2026-09-09T01:00:00Z' } }, who: { status: 'done', text: 'x' } }, events: [cq.event], persons: [] }, { folder: '/tmp/x' });
ok('三层分工与请求协议', doc.includes('排盘引擎') && doc.includes('规则引擎') && doc.includes('【工作台请求解读 #key】') && doc.includes('interpretations["key"]'));
ok('事实 / 信号 / 今年六个方面', doc.includes('四柱：') && doc.includes('真太阳时') && doc.includes('## 信号') && doc.includes('六个方面'));
ok('待写回列表', doc.includes('等你写回的') && doc.includes('`reveal`') && doc.includes('已写回的：`who`'));
ok('问过的事带卦', doc.includes('event:' + cq.event.event_id) && doc.includes('六爻：本卦'));
ok('没有旧的预写解读段落', !doc.includes('展开来说') && !doc.includes('最像自己的时候：'));
ok('文档无垃圾字符', !GARBAGE.test(doc), doc.match(/.{20}(undefined|NaN|\[object Object\]).{20}/)?.[0]);
ok('正文无断言词（开头说话规则除外）', !DOOM.test(doc.split('## 工作台怎么分工')[1] || ''), (doc.split('## 工作台怎么分工')[1] || '').match(/.{20}(必然|注定|宣判|灾|凶).{20}/g)?.join(' | '));
ok('profileFacts 含大运表', profileFacts(prof, bz, zw, corr).includes('大运：'));

console.log('\n[7] 十神颜色 / 地点 / 择日自定义 / 另一条线 / 起名');
ok('十神五行：日主木 → 食伤火、财土、官杀金、印水', tenGodWuxing('食神', '木') === '火' && tenGodWuxing('正财', '木') === '土' && tenGodWuxing('七杀', '木') === '金' && tenGodWuxing('正印', '木') === '水' && tenGodWuxing('比肩', '木') === '木');
const pf = placeFacts(bz, zw, { birth_place: '杭州' });
ok('地点：以出生地为原点，八方位齐全', pf.origin.name === '杭州' && pf.directions.length === 8 && pf.directions.every(d => d.trigram && d.wuxing));
ok('地点：每个方位都分到了城市', pf.directions.filter(d => d.near.length + d.far.length > 0).length >= 6, pf.directions.map(d => `${d.name}${d.near.length + d.far.length}`).join(','));
ok('地点：桃花位与驿马位', pf.taohua.length >= 1 && pf.yima.length >= 1 && pf.taohua.every(t => t.direction));
ok('地点：没填出生地退到北京', placeFacts(bz, zw, {}).origin.source === 'default');
const pfi = placeFacts(bz, zw, { birth_place: '杭州' }, 'intl');
ok('地点国际版：只有海外城市，且分布到多个方位', pfi.scope === 'intl' && pfi.directions.every(d => ![...d.near, ...d.far].some(n => ['上海', '北京', '苏州', '香港'].includes(n))) && pfi.directions.filter(d => d.near.length + d.far.length > 0).length >= 5, pfi.directions.map(d => `${d.name}:${[...d.near, ...d.far].slice(0, 3).join('/')}`).join(' '));
ok('地点国内版：不含海外城市', pf.directions.every(d => ![...d.near, ...d.far].some(n => ['东京', '首尔', '新加坡', '纽约'].includes(n))));
ok('国际版请求 key 不同', buildRequest('places', { ...ctx, places: pfi }).key === 'places:intl' && buildRequest('places', { ...ctx, places: pfi }).prompt.includes('国际版'));
ok('地点文本无垃圾字符', !GARBAGE.test(placeFactsText(pf)) && cityFacts('成都', pf).includes('成都') && cityFacts('火星', pf).includes('不在'));
const pr2 = buildRequest('places', { ...ctx, places: pf });
ok('places 请求：四类地方 + 写回', ['定情之地', '转折之地', '奇遇之地', '安顿之地'].every(w => pr2.prompt.includes(w)) && pr2.prompt.includes('interpretations["places"]'));
ok('择日：自由描述映射', resolveActivity('搬去杭州').key === 'move' && resolveActivity('提离职').matched === false && scoreDay(almanacOf(new Date('2026-10-10T00:00:00')), resolveActivity('提离职'), bz).activity.key === 'generic');
let st2 = S.createProfile({ ...S.EMPTY }, { name: '测', ...base }).state;
const tl = S.addTimeline(st2, { premise: '我没有去新加坡读研究生，而是留在国内读', from_year: 2018 });
st2 = tl.state;
ok('另一条线：只存前提和年份', tl.timeline.premise.includes('新加坡') && tl.timeline.from_year === 2018 && S.activeProfile(st2).timelines.length === 1);
const ar = buildRequest('alt', { ...ctx, timeline: tl.timeline });
ok('alt 请求：不引导职业资产，写另一种可能', ar.key === `alt:${tl.timeline.timeline_id}` && ar.prompt.includes('如果当年……我没有去新加坡') && ar.prompt.includes('不要引导到城市、职业、收入、资产') && ar.prompt.includes('2018'));
const nmat = nameMaterial(bz, '想用到川字');
ok('用字材料：参考信息里的字优先，其余按喜用五行抽', nmat[0].c === '川' && nmat.length >= 10 && nmat.slice(1).every(m => bz.strength.favor.includes(m.wuxing)));
ok('姓氏事实：林 平声属木', surnameFacts('林').known && surnameFacts('林').text.includes('平') && !surnameFacts('龘').known);
ok('起名规则含喜用与声调', nameRules(bz, '林').some(r => r.includes('喜') || r.includes('偏向')) && nameRules(bz, '林').some(r => r.includes('声')));
const nr = buildRequest('naming', { ...ctx, naming: { surname: '林', scene: 'baby', sceneLabel: '给孩子', brief: '清朗一点', length: 2, surnameText: surnameFacts('林').text, rules: nameRules(bz, '林'), material: nmat } });
ok('naming 请求：DSH 来起名，## 标题即姓名，不再给候选让它点评', nr.key.startsWith('naming:') && nr.prompt.includes('请你来起名') && nr.prompt.includes('## 林〇〇') && nr.prompt.includes('可用字参考') && !nr.prompt.includes('工作台按字义、音律、五行先筛出的候选'));
const parsed = parseNamesFromText('前言\n## 林川舟\n字义……\n## 2. 林澈\n……\n**林笃涵**：备选\n## 取舍\n……', '林');
ok('解析 DSH 写回的名字', parsed.join(',') === '林川舟,林澈,林笃涵', parsed.join(','));
const ck = checkName('林', `林${nmat[1].c}${nmat[2].c}`, bz);
ok('核对：字库有的字给五行读音，平仄可算', ck.chars.every(x => x.known) && ck.pattern && ck.pattern.length === 3 && ck.strokes > 0, JSON.stringify(ck).slice(0, 200));
ok('核对：字库没有的字被标出', checkName('林', '林龘', bz).unknown.length === 1 && checkName('林', '林龘', bz).pattern === null);
const pp = S.addPerson(st2, { nickname: '他', kind: 'partner', birthDate: '1990-06-01', birthTime: '13:00', gender: '男', birthPlace: '乌鲁木齐' });
const pc = S.personCharts(pp.person);
ok('合盘的人也按出生地做真太阳时', pp.person.birth_place === '乌鲁木齐' && pc.bazi.pillars[3].zhi !== buildBazi({ date: '1990-06-01', time: '13:00', gender: '男' }).pillars[3].zhi);
ok('所有新提示词无垃圾字符与断言词', ![pr2, ar, nr].some(r => GARBAGE.test(r.prompt) || DOOM.test(noTone(r.prompt))));
const nm1 = S.addNaming(st2, { surname: '林', scene: 'baby', brief: '清朗', length: 2 });
const nm2 = S.addNaming(nm1.state, { surname: '林', scene: 'baby', brief: '清朗', length: 2 });
ok('起名运行会留档且同输入去重', S.activeProfile(nm2.state).namings.length === 1 && nm2.run.surname === '林');
ok('起名 key 只由输入决定（回来能找到 DSH 的推荐）', buildRequest('naming', { ...ctx, naming: { ...nm2.run, sceneLabel: '给孩子' } }).key === `naming:${hashOf('林' + 'baby' + '清朗' + 2)}`);

console.log(`\n结果：${pass} 通过 / ${fail} 失败`);
process.exit(fail ? 1 : 0);
